### ISSUE TITLE
★ saintno1997分享的EFI应该怎么使用

### ISSUE THREAD

**Issue by lakie0605** [Skimige/Inspiron-759x-Hackintosh#2]
您好，看了您的分享，觉得★ saintno1997的EFI很不错，不过也有一些疑问：
1、他的目录结构里面没有EFI文件夹，应该怎么使用，是把所有文件直接复制到EFI文件夹下？还是分别复制到EFI/CLOVER文件夹下？
2、他里面有一个运行这个命令的步骤：python3 update.py --build。这是在系统安装好之后运行，还是在安装系统之前运行？

再次感谢，谢谢！

**Comment by Skimige** [comment]
1. 他提供的有 OpenCore 和 Clover 两种配置，根据自己的需要选择一种（在 Release 页有预构建版本），然后放到 EFI\CLOVER(/OC，取决于你的选择) 下。我还复制了一份 CLOVERX64.efi 到 BOOT\BOOTX64.efi 下
2. 请看节标题 `For building`，如果你自己需要即时构建才使用，不需要的话使用 Release 页的预构建版本即可

**Comment by lakie0605** [comment]
@Skimige 理解了，谢谢
